<a href="https://colab.research.google.com/github/CamiloLezcanoUdea/Clase-python/blob/master/numpy_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import numpy as np
import statistics as stat

p = "Palabra"

arr = np.array([1,3,2,4,5,6,7,8,9,0,9,9,9])

print(arr[0])

print(p[2])


arr1 = np.array([1,3,2,4,5,6,7,8,9,10])
arr2 = np.array([11,12,13,14,15,16,17,18,19,20])

print("Suma", arr1 + arr2)
print("Resta", arr1 - arr2)
print("Multiplicacion", arr1 * arr2)
print("Division", arr1 / arr2)
print("Media", np.mean(arr1), np.mean(arr2))
print("Mediana", np.median(arr1), np.median(arr2))
print("Desviacion estandar", np.std(arr1), np.std(arr2))
print("Moda", stat.mode(arr))
print("Moda con numpy", np.argmax(np.bincount(arr)))

matriz = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

matriz_mode = np.array([[1,9,3],
                   [4,9,6],
                   [7,8,9]])

print("Matriz:", matriz)
print("Transpuesta:", matriz.T)
print("Diagonal principal:", np.diag(matriz))
print("Diagonal principal al reves:", np.fliplr(matriz).diagonal())
print("Suma de la matriz", np.sum(matriz))
print("Media:", np.mean(matriz))
print("Mediana:", np.median(matriz))
print("Desviacion estandar:", np.std(matriz))
print("Valor maximo:", np.max(matriz))
print("Valor minimo:", np.min(matriz))
print("Suma de fila:", np.sum(matriz, axis=1))
print("Suma de columna:", np.sum(matriz, axis=0))
matrizToArray = matriz_mode.flatten()
value, count = np.unique(matrizToArray, return_counts=True)
index_mode = np.argmax(count)
mode = value[index_mode]
print("Moda:", mode)

1
l
Suma [12 15 15 18 20 22 24 26 28 30]
Resta [-10  -9 -11 -10 -10 -10 -10 -10 -10 -10]
Multiplicacion [ 11  36  26  56  75  96 119 144 171 200]
Division [0.09090909 0.25       0.15384615 0.28571429 0.33333333 0.375
 0.41176471 0.44444444 0.47368421 0.5       ]
Media 5.5 15.5
Mediana 5.5 15.5
Desviacion estandar 2.8722813232690143 2.8722813232690143
Moda 9
Moda con numpy 9
Matriz: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpuesta: [[1 4 7]
 [2 5 8]
 [3 6 9]]
Diagonal principal: [1 5 9]
Diagonal principal al reves: [3 5 7]
Suma de la matriz 45
Media: 5.0
Mediana: 5.0
Desviacion estandar: 2.581988897471611
Valor maximo: 9
Valor minimo: 1
Suma de fila: [ 6 15 24]
Suma de columna: [12 15 18]
Moda: 9
